AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  photo-app-users-api-cognito

  Sample SAM Template for photo-app-users-api-cognito

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Runtime: java17
    Architectures:
      - x86_64
    MemorySize: 512
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:
        MY_COGNITO_POOL_APP_CLIENT_ID: AQICAHhDgw/VDl6EXMtb4SlrQcy1PKOoIQktVk+3arjx5xRlwQFYhuoVTUvF0N9aRSmDjKaYAAAAeDB2BgkqhkiG9w0BBwagaTBnAgEAMGIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfo0jCCnrtwBRQJUTAgEQgDWQxPR3FndHir7I6BH8VWiOZ5Wd14NUVTKUI/IjCqunQSpYx1WXMQJWyTuva3MS4/PXY6MjZQ==
        MY_COGNITO_POOL_APP_CLIENT_SECRET: AQICAHhDgw/VDl6EXMtb4SlrQcy1PKOoIQktVk+3arjx5xRlwQGM04kOLqHhIkqBRR0DD9I4AAAAlTCBkgYJKoZIhvcNAQcGoIGEMIGBAgEAMHwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMnpTzUuETM5FDzvwMAgEQgE8hQqs3O9q/yfKrJoPT+P/N5Ju4Ni+vHp4ifIppX+UD6pLmoPsO1UjxNDOOubuDApvxcm1rXxNBA3l5G231/OeDdf+LQ9ztzgFtlk/gJUHE
        MY_COGNITO_POOL_ID: AQICAHhDgw/VDl6EXMtb4SlrQcy1PKOoIQktVk+3arjx5xRlwQFNTxclvrywg42NFd/BQl6MAAAAcjBwBgkqhkiG9w0BBwagYzBhAgEAMFwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMUzr7VZ+lGOnl2yteAgEQgC+cTYZYsxGkG1pHKqfjKE5yFZu04ud3KP//VlERbJhINKT6702AfeQujVvD4ySpFg==

Resources:
  MyApi:  # To include changes made in aws api gateway console
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: OpenAPI.yaml

  CreateUserHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: PhotoAppUsersAPICognito
      Handler: com.appsdeveloperblog.aws.lambda.CreateUserHandler::handleRequest
      Events:
        CreateUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users
            Method: post
            RestApiId:
              Ref: MyApi

  ConfirmUserHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: PhotoAppUsersAPICognito
      Handler: com.appsdeveloperblog.aws.lambda.ConfirmUserHandler::handleRequest
      Events:
        ConfirmUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /confirm
            Method: post
            RestApiId:
              Ref: MyApi

  LoginUserHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: PhotoAppUsersAPICognito
      Handler: com.appsdeveloperblog.aws.lambda.LoginUserHandler::handleRequest
      Events:
        ConfirmUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /login
            Method: post
            RestApiId:
              Ref: MyApi

  AddUserToGroupHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: PhotoAppUsersAPICognito
      Handler: com.appsdeveloperblog.aws.lambda.AddUserToGroupHandler::handleRequest
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'cognito-idp:AdminAddUserToGroup'
              Resource: "arn:aws:cognito-idp:eu-north-1:173952030236:userpool/eu-north-1_phYr4wh57"
      Events:
        AddUserToGroup:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users/{userName}/add-to-group
            Method: post
            RestApiId:
              Ref: MyApi

  GetUserHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: PhotoAppUsersAPICognito
      Handler: com.appsdeveloperblog.aws.lambda.GetUserHandler::handleRequest
      Events:
        GetUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users/me
            Method: get
            RestApiId:
              Ref: MyApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreateUserApi:
    Description: "API Gateway endpoint URL for Prod stage for CreateUserHandler Function"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  CreateUserHandlerFunction:
    Description: "CreateUserHandler Lambda Function ARN"
    Value: !GetAtt CreateUserHandlerFunction.Arn
  CreateUserHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for CreateUserHandler"
    Value: !GetAtt CreateUserHandlerFunctionRole.Arn
